# Site settings
title: Statistical Learning
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  An introduction to modern regression and machine learning techniques.
baseurl: "/math-243"
url: "http://andrewpbray.github.io"
#twitter_username: jekyllrb
#github_username:  jekyll

# Build settings
markdown: kramdown
