---
title: "Lab 6: Trees"
output: 
  html_document: 
    highlight: pygments
    theme: spacelab
---

### When a guest arrives they will count how many sides it has on

In class, we estimated by eye the first split in a classification tree for the following shapely data set. Now let's check to see if our graphical intuition agrees with that of the full classification tree algorithm.

```{r, echo = FALSE, fig.height=4.5, fig.width = 4.8, fig.align='center'}
set.seed(75)
n <- 16
x1 <- runif(n)
x2 <- runif(n)
group <- as.factor(sample(1:3, n, replace = TRUE))
df <- data.frame(x1, x2, group)
df[1, 2] <- .765 # tweaks to make a more interesting configuration
df[9, 1] <- .741
df <- df[-7, ]

library(ggplot2)
ggplot(df, aes(x = x1, y = x2, col = group, shape = group)) +
  geom_point(size = 4) +
  scale_x_continuous(expand = c(0, 0) , limits = c(0, 1)) +
  scale_y_continuous(expand = c(0, 0), limits = c(0, 1)) +
  scale_color_discrete(guide = FALSE) +
  scale_shape_discrete(guide = FALSE) +
  theme_bw()
```

#### 1. Growing the full tree

Use the `trees` package in R to fit a full unpruned tree to this data set, making splits based on the Gini index. You can find the code to do this in the slides from week 8 or in the lab at the end of Chapter 8 in the book.


* * *


### Two Cultures

One of the most influential papers in statistical learning was written by Leo Breiman, who did much of the groundbreaking work with trees: [Statistical Modeling: The Two Cultures](http://projecteuclid.org/download/pdf_1/euclid.ss/1009213726) (*Statistical Science*, 2001, Vol. 16, No. 3, 199–231). 

1. 
- What is one question related to this paper that you'd like to see the class discuss on Wednesday?


