---
title: "Penalized Regression"
output:
  ioslides_presentation:
    incremental: true
---

## Example: Credit {.build}

Can we predict the balance that someone will carry on their credit card?

```{r}
credit <- read.csv("http://www-bcf.usc.edu/~gareth/ISL/Credit.csv")[, -1]
dim(credit)
names(credit)
```


## Least Squares {.build}

```{r}
m1 <- lm(Balance ~ ., data = credit)
m1
```


## Ridge regression {.build}

```{r message = FALSE}
X <- model.matrix(Balance ~ ., data = credit)[, -1]
X[1:2, ]
Y <- credit$Balance
lambdas <- seq(from = 1e-2, to = 1e4, length.out = 100)
library(glmnet)
rm1 <- glmnet(x = X, y = Y, alpha = 0, lambda = lambdas, standardize = TRUE)
dim(coef(rm1))
```

## {.build}

```{r}
rm1$lambda[100]
coef(rm1)[1:4, 100]
coef(m1)[1:4]
```


## {.build}

```{r}
rm1$lambda[5]
coef(rm1)[1:4, 5]
coef(rm1)[1:4, 100]
```

##

```{r, echo = FALSE, eval = FALSE}
l <- log10(rep(lambdas, 3))
a <- as.matrix(coef(rm1)[2:4, ])
v <- c(t(a[, seq(100, 1)]))
coef <- as.factor(rep(row.names(coef(rm1))[2:4], each = length(lambdas)))
df <- data.frame(l, v, coef)

library(ggplot2)
ggplot(df, aes(x = l, y = v, color = coef)) + 
  geom_line()
```



