---
title: "Results"
output:
  ioslides_presentation:
    incremental: true
---

```{r, echo = FALSE, message=FALSE}
source("test-lab-3.R")
library(knitr)
opts_chunk$set(echo = FALSE, message = FALSE)
```

## Scoring 
- Coding errors were corrected
- For each group, calculate
    - train MSE
    - test MSE on full test data set
- Remember: sampling variability!
    

## Training MSE

```{r fig.align='center'}
library(ggplot2)
ggplot(results, aes(x = reorder(group, MSE_train), y = MSE_train)) + 
  geom_point(size = 3) +
  ylim(c(0, .03)) +
  xlab("Group") + 
  ylab("train MSE") + 
  theme(text = element_text(size = 16))
```


## Testing MSE

```{r fig.align='center'}
ggplot(results, aes(x = reorder(group, MSE_test), y = MSE_test)) + 
  geom_point(size = 3) +
  ylim(c(0, .03)) +
  xlab("Group") + 
  ylab("test MSE") + 
  theme(text = element_text(size = 16))
```


## Bias - Variance Tradeoff

```{r fig.align='center'}
res2 <- results
names(res2)[c(3, 4)] <- c("MSE", "MSE")
res2 <- rbind(res2[, 1:3], res2[, c(1, 2, 4)])
res2$data <- c(rep("train", n_groups), rep("test", n_groups))
ggplot(res2, aes(x = p, y = MSE, color = group, shape = data)) +
  geom_point(size = 4, position = "jitter")
```


## Variable usage {.build}

In the top 4 models, the types of variables were used.

### Twice
divorce, children born to never married

### Thrice
urban/density, poverty

### Fource
race





