---
title: "Lab 5: Resampling"
output: 
  html_document: 
    highlight: pygments
    theme: spacelab
---

### Past Performance, Future Results[^1]

A corporation’s **earnings** in a given year is its income minus its expenses. The
return on an investment over a year is the fractional change in its value, $(v_{t+1} - v_t)/v_t$, and the average rate of return over $k$ years is $[(v_{t+k} - v_t)/v_t]^{1/k}$.  Our data set this week looks at the relationship between US stock prices, the earnings of the
corporations, and the returns on investment in stocks, with returns counting both
changes in stock price and dividends paid to stock holders.

Specifically, our data contains the following variables:

- `Date`, with fractions of a year indicating months
- `Price` of an index of US stocks (inflation-adjusted)
- `Earnings` per share (also inflation-adjusted);
- `Earnings_10MA_back`, a ten-year moving average of earnings, looking backwards from the current date;
- `Return_cumul`, cumulative return of investing in the stock index,  from the beginning;
- `Return_10_fwd`, the average rate of return over the next 10 years from the current date.

"Returns" will refer to `Return_10_fwd` throughout.

### 1. Inventing a variable
a. Add a new column, `MAPE` to the data frame, which is the ratio of `Price` to `Earnings_10MA_back`.



[^1]: Based on a homework of Cosma Shalizi at CMU.

